name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}                        
      
      - name: Remove .scannerwork directory
        run: rm -rf .scannerwork

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aandresbarreras/apilat:latest

      - name: Build and push ingest Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api/ingest
          push: true
          tags: aandresbarreras/apilat:latest

      - name: Build and push data Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api/data
          push: true
          tags: aandresbarreras/data:latest
